/**
 * Nominatim OpenStreetMap Geocoding Service
 * 
 * Provides forward and reverse geocoding capabilities using the Nominatim API.
 * Forward geocoding converts area names to coordinates.
 * Reverse geocoding converts coordinates to addresses in Indonesian format.
 * 
 * @see https://nominatim.org/release-docs/latest/api/
 */

// ============================================================================
// Custom Error Class
// ============================================================================

/**
 * Custom error class for Nominatim geocoding-related failures.
 * Wraps errors from network requests, parsing failures, or API errors.
 */
export class NominatimGeocodingError extends Error {
  /** Additional context about where/why the error occurred */
  public readonly code?: string;

  constructor(
    message: string,
    cause?: unknown,
    code?: string
  ) {
    super(message);
    this.name = 'NominatimGeocodingError';
    this.cause = cause;
    this.code = code;

    // Set prototype chain properly
    Object.setPrototypeOf(this, NominatimGeocodingError.prototype);
  }
}

// ============================================================================
// Interface Definitions
// ============================================================================

/**
 * Address components returned by Nominatim reverse geocoding.
 * Contains structured address parts that can be used to build custom formats.
 */
export interface NominatimAddressComponents {
  /** House number */
  house_number?: string;
  /** Road/street name */
  road?: string;
  /** Suburb/neighbourhood */
  neighbourhood?: string;
  /** Quarter/district */
  quarter?: string;
  /** City/district level 3 */
  city_district?: string;
  /** City/town/village */
  city?: string;
  /** Town */
  town?: string;
  /** Village */
  village?: string;
  /** Suburbs at level 4 */
  suburb?: string;
  /** State/province */
  state?: string;
  /** Country code (ISO 3166-1 alpha-2) */
  country_code?: string;
  /** Country name */
  country?: string;
  /** Postcode */
  postcode?: string;
  /** County */
  county?: string;
  /** Region */
  region?: string;
}

/**
 * Response structure from Nominatim reverse geocoding endpoint.
 * Contains the full address details for a specific latitude/longitude.
 */
export interface NominatimReverseResponse {
  /** Place ID uniquely identifying this location */
  place_id: number;
  /** Licence information */
  licence: string;
  /** OSM node ID if available */
  osm_type?: string;
  /** OSM relation ID if available */
  osm_id?: number;
  /** Latitude (decimal degrees) */
  lat: string;
  /** Longitude (decimal degrees) */
  lon: string;
  /** Display name as generated by Nominatim */
  display_name: string;
  /** Address object with structured components */
  address: NominatimAddressComponents;
  /** Bounding box of the place */
  boundingbox: [string, string, string, string];
  /** Type of feature (e.g., "house", "road", "city") */
  type: string;
  /** Place rank (importance indicator) */
  place_rank: number;
  /** Category type (e.g., "building", "highway") */
  category_type?: string;
  /** Whether this item is a valid address */
  named: boolean;
}

/**
 * Response structure from Nominatim forward geocoding endpoint.
 * Returns a list of potential matches for a search query.
 */
export interface NominatimForwardResponse {
  /** Place ID uniquely identifying this location */
  place_id: number;
  /** License information */
  licence: string;
  /** OSM type identifier */
  osm_type?: string;
  /** OSM ID */
  osm_id?: number;
  /** Lat/lon centroid */
  boundingbox: [string, string, string, string];
  /** Centre point latitude */
  lat: string;
  /** Centre point longitude */
  lon: string;
  /** Display name shown in results */
  display_name: string;
  /** Name of the place */
  name?: string;
  /** Type of place */
  type?: string;
  /** Additional classification tags */
  class?: string;
  /** Structured address components */
  address: NominatimAddressComponents;
  /** Importance score (0-1) */
  importance: number;
  /** Icon URL for result */
  icon?: string;
  /** Associated Wikipedia page URL */
  wikipedia?: string;
}

/**
 * Geocoding query options for forward geocoding searches.
 */
export interface ForwardGeocodeOptions {
  /** Limit number of results (default: 5) */
  limit?: number;
  /** Country codes to restrict search (e.g., "ID" for Indonesia) */
  countrycodes?: string;
  /** Return only addresses matching these types */
  bounded?: boolean;
  /** Custom user agent header value (required by Nominatim) */
  userAgent?: string;
}

/**
 * Reverse geocoding query options.
 */
export interface ReverseGeocodeOptions {
  /** Custom timeout in milliseconds */
  timeout?: number;
  /** Include additional extratags (default: false) */
  extratags?: boolean;
  /** Accept-language parameter for localized results */
  acceptLanguage?: string;
}

// ============================================================================
// Constants
// ============================================================================

/** Base URL for Nominatim API */
const NOMINATIM_BASE_URL = 'https://nominatim.openstreetmap.org';

/** Default timeout for API requests (in milliseconds) */
const DEFAULT_TIMEOUT_MS = 10000;

/** Default request timeout headers */
const DEFAULT_HEADERS = {
  'Accept': 'application/json',
  'User-Agent': 'RecapTestDrive/1.0 (geocoding service)',
};

/** Maximum results for forward geocoding */
const DEFAULT_LIMIT = 5;

/** Minimum confidence score for valid results */
const MIN_IMPORTANCE_SCORE = 0.1;

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Validates coordinate inputs for reverse geocoding.
 * Throws GeocodingError if coordinates are invalid.
 * 
 * @param lat - Latitude in decimal degrees (-90 to 90)
 * @param lon - Longitude in decimal degrees (-180 to 180)
 */
function validateCoordinates(lat: number, lon: number): void {
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) {
    throw new NominatimGeocodingError(
      'Latitude and longitude must be finite numbers',
      undefined,
      'INVALID_COORDINATES'
    );
  }

  if (lat < -90 || lat > 90) {
    throw new NominatimGeocodingError(
      `Invalid latitude: ${lat}. Must be between -90 and 90`,
      { lat },
      'INVALID_LATITUDE'
    );
  }

  if (lon < -180 || lon > 180) {
    throw new NominatimGeocodingError(
      `Invalid longitude: ${lon}. Must be between -180 and 180`,
      { lon },
      'INVALID_LONGITUDE'
    );
  }
}

/**
 * Creates a fetch controller with timeout capability.
 * 
 * @param timeoutMs - Timeout in milliseconds
 * @returns Object with signal and cleanup method
 */
function createTimeoutController(timeoutMs: number): {
  signal: AbortSignal;
  clearRequest: () => void;
} {
  const controller = new AbortController();
  let timeoutId: ReturnType<typeof setTimeout> | null = setTimeout(() => controller.abort(), timeoutMs);
  
  // Clean up timeout on successful completion
  return {
    signal: controller.signal,
    clearRequest: () => {
      if (timeoutId) {
        clearTimeout(timeoutId);
        timeoutId = null;
      }
    },
  };
}

/**
 * Parses JSON response with error handling.
 * 
 * @param response - Fetch response object
 * @returns Parsed JSON data
 */
async function parseJsonResponse<T>(response: Response): Promise<T> {
  if (!response.ok) {
    let errorMessage = `HTTP ${response.status}`;
    
    try {
      const errorData = await response.text();
      errorMessage = errorData || errorMessage;
    } catch {
      // Ignore parsing errors, use status code message
    }

    throw new NominatimGeocodingError(
      `Geocoding API request failed: ${errorMessage}`,
      { status: response.status },
      'API_REQUEST_FAILED'
    );
  }

  try {
    return await response.json() as T;
  } catch (error: unknown) {
    throw new NominatimGeocodingError(
      `Failed to parse API response: ${error instanceof Error ? error.message : 'Unknown error'}`,
      error,
      'PARSE_ERROR'
    );
  }
}

// ============================================================================
// Main Service Functions
// ============================================================================

/**
 * Formats an address from Nominatim response into Indonesian style.
 * 
 * The format follows: Jalan + Kec + Kab + Prov pattern commonly used in Indonesia.
 * - Jalan: Street/road name
 * - Kec: Kecamatan (district)
 * - Kab: Kabupaten (regency/city)
 * - Prov: Provinsi (province/state)
 * 
 * Example: "Jl. Sudirman, Kec. Menteng, Jakarta Pusat, DKI Jakarta"
 * 
 * @param response - Nominatim reverse geocoding response
 * @returns Formatted Indonesian-style address string
 */
export function formatIndonesianAddress(response: NominatimReverseResponse): string {
  const { address } = response;
  const parts: string[] = [];

  // 1. Street/Road component
  if (address.road) {
    // Convert common street abbreviations
    let street = address.road.trim();
    
    // Normalize common prefixes
    street = street.replace(/^Jalan\s+/i, '');
    street = street.replace(/^Jl\./i, 'Jl.');
    
    if (!/^Jl\.|^Jalan\b/i.test(street)) {
      street = 'Jl. ' + street;
    }
    
    parts.push(street);
  } else if (address.neighbourhood) {
    parts.push(address.neighbourhood);
  }

  // 2. District/Kecamatan component
  if (address.suburb || address.quarter) {
    const district = address.suburb || address.quarter;
    parts.push(`Kec. ${district}`);
  }

  // 3. City/Regency/Kabupaten component
  if (address.city || address.county) {
    const cityComponent = address.city ?? address.county;
    
    // Type guard to ensure cityComponent is a valid string
    if (!cityComponent) {
      return response.display_name;
    }
    
    // Check if this is a regency (kabupaten) or city (kota)
    let cityText = cityComponent;
    
    // Common regency indicators in Indonesia
    const kabupatenPatterns = [
      /kabupaten/i,
      /regensi/i,
      /\b(kota|kotamadya)\b/i
    ];
    
    for (const pattern of kabupatenPatterns) {
      if (pattern.test(cityComponent)) {
        cityText = cityComponent.replace(pattern, '').trim();
        break;
      }
    }
    
    if (cityText && cityText.length > 0) {
      parts.push(`Kab. ${cityText}`);
    }
  }

  // 4. Province/Provinsi component
  if (address.state || address.region) {
    const province = address.state ?? address.region;
    if (province && province !== 'Indonesia') {
      // Add province prefix for clarity
      parts.push(`Prov. ${province}`);
    }
  }

  // 5. Optional: Postcode
  if (address.postcode) {
    parts.push(`Pos: ${address.postcode}`);
  }

  // Join all components with comma separator
  return parts.length > 0 ? parts.join(', ') : response.display_name;
}

/**
 * Performs reverse geocoding - converts latitude/longitude to address.
 * 
 * Given coordinates, retrieves the human-readable address from Nominatim API
 * and returns it formatted according to Indonesian addressing conventions.
 * 
 * @param lat - Latitude in decimal degrees (-90 to 90)
 * @param lon - Longitude in decimal degrees (-180 to 180)
 * @param options - Optional configuration settings
 * @returns Promise resolving to formatted Indonesian address string
 * @throws GeocodingError if coordinates are invalid or API request fails
 * 
 * @example
 * ```typescript
 * const address = await reverseGeocode(-6.2088, 106.8456);
 * // Returns: "Jl. Medan Merdeka Selatan, Kec. Gambir, Jakarta Pusat, DKI Jakarta"
 * ```
 */
export async function reverseGeocodeStructured(
  lat: number,
  lon: number,
  options: ReverseGeocodeOptions = {}
): Promise<NominatimReverseResponse> {
  const { timeout = DEFAULT_TIMEOUT_MS } = options;

  try {
    // Validate coordinates
    validateCoordinates(lat, lon);

    // Create abort controller with timeout
    const controller = createTimeoutController(timeout);

    // Build query parameters
    const params = new URLSearchParams({
      lat: lat.toFixed(6),
      lon: lon.toFixed(6),
      format: 'json',
      addressdetails: '1',
      'namedetails': '1',
    });

    // Add optional parameters
    if (options.extratags) {
      params.set('extratags', '1');
    }

    if (options.acceptLanguage) {
      params.set('acceptlanguage', options.acceptLanguage);
    }

    // Make API request
    const url = `${NOMINATIM_BASE_URL}/reverse?${params.toString()}`;

    const response = await fetch(url, {
      method: 'GET',
      headers: DEFAULT_HEADERS,
      signal: controller.signal,
    });

    // Clear timeout on success
    controller.clearRequest();

    // Parse and return the structured response
    return await parseJsonResponse<NominatimReverseResponse>(response);

  } catch (error: unknown) {
    // Re-throw known errors, wrap others
    if (error instanceof NominatimGeocodingError) {
      throw error;
    }

    throw new NominatimGeocodingError(
      `Reverse geocoding failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
      error,
      'REVERSE_GEOCODING_FAILED'
    );
  }
}

export async function reverseGeocode(
  lat: number,
  lon: number,
  options: ReverseGeocodeOptions = {}
): Promise<string> {
  const apiResponse = await reverseGeocodeStructured(lat, lon, options);
  return formatIndonesianAddress(apiResponse);
}

/**
 * Performs forward geocoding - searches for places by name/description.
 * 
 * Searches the Nominatim database for locations matching the given query,
 * such as area names, streets, cities, or landmarks. Returns the top result
 * if a match is found.
 * 
 * @param query - Search query (area name, street, city, landmark, etc.)
 * @param options - Query configuration options (optional parameters)
 * @returns Promise resolving to the best matching NominatimForwardResponse
 * @throws GeocodingError if query is empty, no results found, or API request fails
 * 
 * @example
 * ```typescript
 * const result = await forwardGeocode('Monas, Jakarta');
 * // Returns: { lat: "-6.175392", lon: "106.827153", ... }
 * ```
 */
export async function forwardGeocode(
  query: string,
  options?: ForwardGeocodeOptions
): Promise<NominatimForwardResponse> {
  const limit = options?.limit ?? DEFAULT_LIMIT;
  const countrycodes = options?.countrycodes ?? 'id'; // Default to Indonesia for better accuracy

  try {
    // Validate query
    if (!query || typeof query !== 'string' || query.trim().length === 0) {
      throw new NominatimGeocodingError(
        'Search query cannot be empty',
        undefined,
        'EMPTY_QUERY'
      );
    }

    const trimmedQuery = query.trim();

    // Create abort controller with timeout
    const controller = createTimeoutController(DEFAULT_TIMEOUT_MS);

    // Build query parameters
    const params = new URLSearchParams({
      q: trimmedQuery,
      format: 'json',
      addressdetails: '1',
      limit: limit.toString(),
    });

    // Add country code restriction if provided
    if (countrycodes) {
      params.set('countrycodes', countrycodes);
    }

    // Make API request
    const url = `${NOMINATIM_BASE_URL}/search?${params.toString()}`;

    const headers: Record<string, string> = {
      ...DEFAULT_HEADERS,
    };

    if (options?.userAgent) {
      headers['User-Agent'] = options.userAgent;
    }

    const response = await fetch(url, {
      method: 'GET',
      headers,
      signal: controller.signal,
    });

    // Clear timeout on success
    controller.clearRequest();

    // Handle non-OK responses
    if (!response.ok) {
      if (response.status === 429) {
        throw new NominatimGeocodingError(
          'Rate limit exceeded. Please slow down your requests.',
          { status: response.status },
          'RATE_LIMIT_EXCEEDED'
        );
      }

      let errorMessage = `HTTP ${response.status}`;
      try {
        const errorData = await response.text();
        errorMessage = errorData || errorMessage;
      } catch {
        // Ignore parsing errors
      }

      throw new NominatimGeocodingError(
        `Forward geocoding failed: ${errorMessage}`,
        { status: response.status },
        'FORWARD_GEOCODING_FAILED'
      );
    }

    // Parse response array
    let results: NominatimForwardResponse[];
    try {
      results = await response.json() as NominatimForwardResponse[];
    } catch (error: unknown) {
      throw new NominatimGeocodingError(
        `Failed to parse API response: ${error instanceof Error ? error.message : 'Unknown error'}`,
        error,
        'PARSE_ERROR'
      );
    }

    // Validate results
    if (results.length === 0) {
      throw new NominatimGeocodingError(
        `No results found for query: "${trimmedQuery}"`,
        { query: trimmedQuery },
        'NO_RESULTS_FOUND'
      );
    }

    // Filter results by importance score (confidence threshold)
    const qualifiedResults = results.filter(result => 
      result.importance >= MIN_IMPORTANCE_SCORE
    );

    if (qualifiedResults.length === 0) {
      throw new NominatimGeocodingError(
        `No suitable results found for query: "${trimmedQuery}". Results had low confidence scores.`,
        { query: trimmedQuery },
        'LOW_CONFIDENCE'
      );
    }

    // Sort by importance and return best match
    const bestMatch = qualifiedResults.sort((a, b) => b.importance - a.importance)[0];

    if (!bestMatch.lat || !bestMatch.lon) {
      throw new NominatimGeocodingError(
        'Location has no valid coordinates',
        bestMatch,
        'INVALID_COORDINATES'
      );
    }

    return bestMatch;

  } catch (error: unknown) {
    // Re-throw known errors, wrap others
    if (error instanceof NominatimGeocodingError) {
      throw error;
    }

    throw new NominatimGeocodingError(
      `Forward geocoding failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
      error,
      'FORWARD_GEOCODING_ERROR'
    );
  }
}

/**
 * Convenience wrapper for searching by area name with default Indonesian bounds.
 * Simplifies forward geocoding for Indonesian locations.
 * 
 * @param areaName - Name of the area, district, city, or landmark
 * @param limit - Maximum number of results to consider (default: 3)
 * @returns Promise resolving to the best matching location
 */
export async function searchByAreaName(
  areaName: string,
  limit?: number
): Promise<NominatimForwardResponse> {
  const config: ForwardGeocodeOptions = {
    countrycodes: 'id',
  };
  
  if (limit !== undefined) {
    config.limit = limit;
  }
  
  return forwardGeocode(areaName, config);
}

/**
 * Checks if a location string might represent a valid address or place name.
 * Used to determine whether geocoding is necessary before attempting a call.
 * 
 * @param text - Text to validate
 * @returns True if the text appears to be a valid geocoding candidate
 */
export function isValidGeocodeQuery(text: string): boolean {
  if (!text || typeof text !== 'string') {
    return false;
  }

  const cleaned = text.trim();
  return cleaned.length >= 2 && cleaned.length <= 500;
}

/**
 * Converts decimal degrees to degrees-minutes-seconds (DMS) format.
 * Useful for displaying coordinates in traditional formats.
 * 
 * @param decimal - Coordinate in decimal degrees
 * @returns Object with degrees, minutes, seconds, and direction
 */
export function toDMS(decimal: number): {
  d: number;
  m: number;
  s: number;
  dir: string;
} {
  const isNegative = decimal < 0;
  const absDecimal = Math.abs(decimal);

  const d = Math.floor(absDecimal);
  const mDec = (absDecimal - d) * 60;
  const m = Math.floor(mDec);
  const s = ((mDec - m) * 60).toFixed(2);

  return {
    d,
    m,
    s: parseFloat(s.toString()),
    dir: isNegative ? (isNaN(decimal) ? '' : (Math.abs(decimal) > 90 ? 'S' : 'W')) : (Math.abs(decimal) > 90 ? 'N' : 'E'),
  };
}
